# Generated by Django 5.2.1 on 2025-05-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_id', models.CharField(max_length=100, unique=True)),
                ('numero', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_con_iva', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
