# Generated by Django 5.2.1 on 2025-05-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='factura_id',
            new_name='factura_id_unico',
        ),
    ]
