# Generated by Django 5.2.1 on 2025-05-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_rename_factura_id_factura_factura_id_unico'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.CharField(max_length=100, unique=True)),
                ('cliente', models.CharField(max_length=100)),
                ('ingresos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_ventas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gastos_operativos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('otros_ingresos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('otros_gastos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ganancia_bruta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ganancia_operativa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('resultado_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('margen_bruto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('margen_operativo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('margen_neto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(max_length=20)),
                ('riesgo', models.CharField(max_length=20)),
            ],
        ),
    ]
