# Generated by Django 5.1.5 on 2025-05-27 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areasContables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('asiento', models.CharField(blank=True, max_length=10)),
                ('cuenta', models.CharField(max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('concepto', models.TextField(blank=True)),
                ('debe', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='areasContables.facturaarchivo')),
            ],
        ),
    ]
