# Generated by Django 5.1.5 on 2025-05-28 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areasContables', '0002_lineafactura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacontable',
            name='afirmaciones_afectadas',
        ),
        migrations.AlterField(
            model_name='facturaarchivo',
            name='archivo',
            field=models.FileField(upload_to='archivos_facturas/'),
        ),
        migrations.CreateModel(
            name='SubAreaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('codigos_positivos', models.CharField(help_text="Ej: '201,202'", max_length=255)),
                ('codigos_negativos', models.CharField(blank=True, default='', help_text="Ej: '2811,2901'", max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subareas', to='areasContables.areacontable')),
            ],
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='subarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas', to='areasContables.subareacontable'),
        ),
    ]
