# Generated by Django 5.1.5 on 2025-05-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areasContables', '0003_remove_areacontable_afirmaciones_afectadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacontable',
            name='afirmaciones_afectadas',
            field=models.TextField(blank=True, default='', help_text='Lista de afirmaciones afectadas, separadas por coma'),
        ),
    ]
