# Generated by Django 5.1.5 on 2025-05-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areasContables', '0004_areacontable_afirmaciones_afectadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineafactura',
            name='factura',
        ),
        migrations.DeleteModel(
            name='FacturaArchivo',
        ),
    ]
