# Generated by Django 5.1.5 on 2025-05-29 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areasContables', '0005_remove_lineafactura_factura_delete_facturaarchivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('letra', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='areacontable',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='areasContables.seccioncontable'),
        ),
    ]
